# -*- coding: utf-8 -*-
"""Beeper_path

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14ZbZ5VBNprRGNRJq_LLm9M9gxFOK_9VR
"""

from karel.stanfordkarel import *

def main():
    #take karel home
    while beepers_present():
        move()







if __name__ == '__main__':
    main()