# -*- coding: utf-8 -*-
"""put beepers

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dtrsZi9TZUZVHW2bI71VCmMBPO2V-dxy
"""

from karel.stanfordkarel import *

"""
When you finish writing this file, Karel should be able to
place 20 beepers, then 26 beepers, and end facing East to
the right of the 26 beepers.
"""

def main():
    for i in range(20):
        put_beeper()
    move()
    for i in range(26):
        put_beeper()
    move()