# -*- coding: utf-8 -*-
"""piles

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xoX9i14K6FvZD3s1y62u_zhc_r1_4FRM
"""

from karel.stanfordkarel import *

# File: piles.py
# -----------------------------
# The warmup program defines a "main"
# function which should make Karel
# pick up all the beepers in the world.
def main():
    for i in range(3): #the beeker is picked 30 times in 3 rounds
        pick()
        move()

# picking up beeper

def pick():
    move()
    for i in range(10):
        pick_beeper()