# -*- coding: utf-8 -*-
"""Jigsaw_karel

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ociqy4ZZueqUdgycDGiiNSG_AuQnsrJe
"""

from karel.stanfordkarel import *

"""
Karel should finish the puzzle by picking up the last beeper
(puzzle piece) and placing it in the right spot. Karel should
end in the same position Karel starts in -- the bottom left
corner of the world.
"""


def main():
    # picking up bepper
    move()
    move()
    pick_beeper()
    move()

    #moving upwards
    turn_left()
    move()
    move()

    # placing beeker
    put_beeper()

    return_karel()




#returning karel to starting position

def return_karel():
    turn_left()
    turn_left()
    move()
    move()
    turn_left()
    turn_left()
    turn_left()
    move()
    move()
    move()
    turn_left()
    turn_left()










# There is no need to edit code beyond this point
if __name__ == '__main__':
    main()